version: '3.8'

services:
  scrape:
    build: ./scrape
    container_name: scrape
    working_dir: /scrape
    volumes:
    - ./scrape:/scrape
    command: python3 /scrape/artists.py

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant:/qdrant/storage
    depends_on:
      - scrape

  app:
    build: ./app
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app
    command:
    depends_on:
      - qdrant

configs:
  qdrant_config:
    content: |
      log_level: INFO